#substitutions:
#  _DF_ZONE: us-central1-a
#  _DF_CLUSTER: spring-app-cluster

steps:
  # This is untested, but should work basically.
  - name: gcr.io/cloud-builders/mvn
    entrypoint: bash
    args:
      - -c
      - |
        ln -s /builder/home/.docker /root/.docker &&
        mvn -B compile com.google.cloud.tools:jib-maven-plugin:build -Dimage=gcr.io/$PROJECT_ID/app -Dtags=${SHORT_SHA},latest,teste

#  #step 3: Apply kubernetes config files
#  - name: 'gcr.io/cloud-builders/kubectl'
#    args: ['apply', '-f', 'k8s/']
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=spring-app-cluster'
#
#  #step 4: Deploy app
#  - name: 'gcr.io/cloud-builders/kubectl'
#    args: [
#      'set',
#      'image',
#      'deployment',
#      'spring-jib-deployment',
#      'spring-jib-app=gcr.io/$PROJECT_ID/app:$SHORT_SHA'
#    ]
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=spring-app-cluster'

images: [
  'gcr.io/$PROJECT_ID/app:$SHORT_SHA',
  'gcr.io/$PROJECT_ID/app:latest'
]